### PR TITLE
We dont have a license yet

### PR DESCRIPTION
**Pull request by wmaciel**

### CODE REVIEW

**Comment by ebabel** [comment]
A [background service](https://developer.android.com/training/run-background-service/create-service.html) would be a nice feature to add. So you can pull up maps, texting, camera, or whatever and still be logging.

**Comment by ebabel** [comment]
Might make unit/instrumentation testing more difficult though.

**Comment by ebabel** [comment]
@kwatkins MIT license ok with you?

**Comment by kwatkins** [comment]
Love me some MIT

**Pull request merged**
